codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: 50...100

  status:
    project: true
    path: true
    changes: true
    
ignore:
- 'CMake'
- 'Extensions'
- 'Includes'
- 'Libraries'
- 'Scripts'
- 'Resources'
- 'Documents'

comment:
  layout: "header, diff, changes, uncovered"
  behavior: default