FROM ubuntu:19.04
LABEL maintainer "JYPark09 <jyp10987@gmail.com>"

RUN apt update && apt install -y \
	build-essential \
	cmake \
	clang-8 \
	libx11-dev \
	freeglut3-dev \
	libudev-dev \
	libxrandr-dev \
	libfreetype6-dev \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

COPY . /app

WORKDIR /app/build
RUN cmake .. -DCMAKE_C_COMPILER=clang-8 -DCMAKE_CXX_COMPILER=clang++-8 && \
	make -j "$(nproc)" && \
	make install && \
	bin/UnitTest

WORKDIR /